=== AlitaBernachot/ogc-client/fixtures/ogc-api/sample-data/collections/airports/schemas/feature.json
{
  "title": "Airports",
  "description": "A centre point for all major airports including a name.",
  "properties": {
    "type": {
      "type": "string",
      "enum": ["Feature"]
    },
    "links": {
      "items": {
        "$ref": "#/$defs/Link"
      },
      "type": "array"
    },
    "id": {
      "type": "integer"
    },
    "geometry": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "title": "GeoJSON Point",
          "properties": {
            "type": {
              "type": "string",
              "enum": ["Point"]
            },
            "coordinates": {
              "items": {
                "type": "number"
              },
              "minItems": 2,
              "maxItems": 3,
              "type": "array"
            }
          },
          "type": "object",
          "required": ["type", "coordinates"]
        }
      ]
    },
    "properties": {
      "properties": {
        "name": {
          "title": "Name",
          "type": "string"
        }
      },
      "type": "object"
    }
  },
  "type": "object",
  "required": ["type", "geometry", "properties"],
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://my.server.org/sample-data/collections/airports/schemas/feature",
  "$defs": {
    "Link": {
      "properties": {
        "href": {
          "format": "uri-reference",
          "type": "string"
        },
        "rel": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      },
      "type": "object",
      "required": ["href"]
    }
  }
}

=== AlitaBernachot/ogc-client/fixtures/ogc-api/sample-data/collections/airports/items/1.json
{
  "type": "Feature",
  "id": 1,
  "geometry": { "type": "Point", "coordinates": [-1.2918826, 59.8783475] },
  "properties": { "name": "Sumburgh Airport" },
  "links": [
    {
      "href": "https://demo.ldproxy.net/zoomstack/collections/airports/items/1?f=json",
      "rel": "self",
      "type": "application/geo+json",
      "title": "This document"
    },
    {
      "href": "https://demo.ldproxy.net/zoomstack/collections/airports/items/1?f=jsonfgc",
      "rel": "alternate",
      "type": "application/vnd.ogc.fg+json;compatibility=geojson",
      "title": "This document as JSON-FG (GeoJSON Compatibility Mode)"
    },
    {
      "href": "https://demo.ldproxy.net/zoomstack/collections/airports/items/1?f=fgb",
      "rel": "alternate",
      "type": "application/flatgeobuf",
      "title": "This document as FlatGeobuf"
    },
    {
      "href": "https://demo.ldproxy.net/zoomstack/collections/airports/items/1?f=html",
      "rel": "alternate",
      "type": "text/html",
      "title": "This document as HTML"
    },
    {
      "href": "https://demo.ldproxy.net/zoomstack/collections/airports/items/1?f=jsonfg",
      "rel": "alternate",
      "type": "application/vnd.ogc.fg+json",
      "title": "This document as JSON-FG"
    },
    {
      "href": "https://demo.ldproxy.net/zoomstack/collections/airports?f=json",
      "rel": "collection",
      "type": "application/json",
      "title": "The collection the feature belongs to"
    }
  ]
}
